apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-geo
    name: api-geo
    type: web
  name: api-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-geo
      name: api-geo
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-geo
        name: api-geo
        type: web
      name: api-geo
    spec:
      containers:
      - image: sheriff/api-geo:1.0.{{build.number}}
        imagePullPolicy: IfNotPresent
        name: api-geo
        ports:
        - containerPort: 3001
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quayregistrykey
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
